	function typing() {
		var $input = $('.sc2_img01_txt input');
		var startTime = 0;
		var typeTime = 0.05;
		var tl = new TimelineMax();
		tl.addCallback(function(){$input.val('ㅊ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추ㅊ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추처');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천ㅋ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키ㅇ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키우');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워ㄷ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 :');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : ㅇ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우ㄷ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대ㄱ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대그');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금ㄹ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리,');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, ㅇ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 이');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인ㅌ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터ㄴ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터네');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷ㄷ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대ㅊ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대추');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출,');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, ㅁ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모ㅂ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바ㅇ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바이');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일ㅂ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일배');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일뱅');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일뱅ㅋ');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일뱅키');}, startTime += typeTime);
		tl.addCallback(function(){$input.val('추천키워드 : 우대금리, 인터넷대출, 모바일뱅킹');}, startTime += typeTime);
		tl.play();
	}

	// $(window).on('load',function () {
	// 	typing();
	// });
